# version: '3'
# services:
#   postgres:
#     container_name: postgres_container
#     image: postgres:16
#     environment:
#       POSTGRES_USER: yourUser
#       POSTGRES_PASSWORD: yourPass
#       POSTGRES_DB: todos
#     ports:
#       - 5432:5432

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - todos
    restart: always

  app:
    image: aws-ecs-fargate-nodejs-todo-app:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todos
    restart: always

networks:
  todos: