version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: yourUser
      POSTGRES_PASSWORD: yourPass
      POSTGRES_DB: todos
    ports:
      - 5432:5432
